{"name": "test_login_check", "status": "failed", "statusDetails": {"message": "AssertionError: failed to check login information\nassert False == True", "trace": "self = <src.tests.test_1_login.TestLogin object at 0x0000027BCA39EE00>, login_page = <src.pages.LoginPage.LoginPage object at 0x0000027BC9E8A410>\n\n    def test_login_check(self, login_page):\n        result = login_page.is_login_successful()\n    \n>       assert result == True, \"failed to check login information\"\nE       AssertionError: failed to check login information\nE       assert False == True\n\nsrc\\tests\\test_1_login.py:35: AssertionError"}, "start": 1744594536504, "stop": 1744594536807, "uuid": "69c51150-57c8-4dd4-a79b-82fd66724b38", "historyId": "8b84eff170768a200ca3fe9a658a2690", "testCaseId": "8b84eff170768a200ca3fe9a658a2690", "fullName": "src.tests.test_1_login.TestLogin#test_login_check", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Perry"}, {"name": "thread", "value": "17264-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_1_login"}]}