{"uuid": "a386ffd1-f710-4219-bf8f-0303ba6e7be7", "children": ["2bc891b8-d02a-4d50-a9fa-98c9da10d338", "110aef6b-3892-44e6-8aaf-370cc8e4341a", "4d2d1923-9c78-4856-a444-e2efce0fffd9", "b656ceea-2382-4f18-83f1-bef039e71d34", "2c4c9006-cb3a-4d28-9377-4ef0774bbfa9", "e402ba46-ddc9-453f-b5dd-3e3286fb099a", "991cf28d-a11b-4235-b9d5-7aa9ed8eb089", "61b26e11-bfd6-4b30-8bfc-2225db408a63"], "befores": [{"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332454584, "stop": 1739332454587}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332456613, "stop": 1739332456616}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332458694, "stop": 1739332458700}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332460754, "stop": 1739332460757}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332462817, "stop": 1739332462819}], "start": 1739332462817, "stop": 1739332462843}