{"name": "test_login_check", "status": "failed", "statusDetails": {"message": "AssertionError: failed to check login information\nassert False == True", "trace": "self = <tests.test_1_login.TestLogin object at 0x000002858D472500>, login_page = <pages.LoginPage.LoginPage object at 0x000002858D4CB0D0>\n\n    def test_login_check(self, login_page):\n        result = login_page.is_login_successful()\n    \n>       assert result == True, \"failed to check login information\"\nE       AssertionError: failed to check login information\nE       assert False == True\n\nsrc\\tests\\test_1_login.py:35: AssertionError"}, "start": 1739329366242, "stop": 1739329366572, "uuid": "9c83404e-2e67-455e-8810-0fbf5a9e983f", "historyId": "8b84eff170768a200ca3fe9a658a2690", "testCaseId": "8b84eff170768a200ca3fe9a658a2690", "fullName": "src.tests.test_1_login.TestLogin#test_login_check", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Perry"}, {"name": "thread", "value": "25148-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_1_login"}]}