{"uuid": "15a09d54-eefe-4e46-ac2d-c9ca403964a5", "children": ["65a6e173-10b6-4e75-90ea-ebeffee731df", "81b873fb-2506-453e-b24c-8e2db41793a6", "02624bc8-0b36-4fec-8c9e-b38e3d356e16", "4d148d36-81a4-4101-b35f-0000302dc5ab", "e0fd29da-3a92-4765-9954-3a252d601207", "80c146f3-b025-489f-b2f3-753cf83997ef", "f07c86ac-d48c-4c3b-9289-25c325488f38", "42010f9b-66be-49d3-913c-cbba8e0d3ab1", "64fc2b85-c41d-411a-a71d-05a447086382", "faf3702a-2a9a-4dee-9471-4d2677ce95d4", "b42fc7da-407b-4f9b-841a-6ff9a1135030", "edddf03f-aa6f-4099-9b61-cf0eb79f3440", "418906d2-306a-4873-b2c5-2f744b0e3a05", "3f83f38f-5852-465e-b5c4-316a96e759bd", "779535fa-e2e9-4af7-a1ad-c5836b7d205f", "f7d3c401-e556-41d0-aa2f-17be4122c1b9", "82563e3f-56e8-452c-bf13-3df451a74357", "1b7dc6f7-476c-47b9-9a8f-b7a6d70b2ec4"], "befores": [{"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332435967, "stop": 1739332435970}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332438002, "stop": 1739332438006}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332440062, "stop": 1739332440065}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332442136, "stop": 1739332442138}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332444194, "stop": 1739332444197}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332446260, "stop": 1739332446267}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332448336, "stop": 1739332448341}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332450411, "stop": 1739332450418}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332452485, "stop": 1739332452493}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332454555, "stop": 1739332454557}], "start": 1739332454555, "stop": 1739332454581}