{"name": "test_login_check", "status": "failed", "statusDetails": {"message": "AssertionError: failed to check login information\nassert False == True", "trace": "self = <tests.test_1_login.TestLogin object at 0x0000012DAD208CD0>, login_page = <pages.LoginPage.LoginPage object at 0x0000012DAD253D60>\n\n    def test_login_check(self, login_page):\n        result = login_page.is_login_successful()\n    \n>       assert result == True, \"failed to check login information\"\nE       AssertionError: failed to check login information\nE       assert False == True\n\nsrc\\tests\\test_1_login.py:35: AssertionError"}, "start": 1738554694027, "stop": 1738554694342, "uuid": "9f6227be-951a-49dd-b491-4a8d38d4b3c2", "historyId": "8b84eff170768a200ca3fe9a658a2690", "testCaseId": "8b84eff170768a200ca3fe9a658a2690", "fullName": "src.tests.test_1_login.TestLogin#test_login_check", "labels": [{"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "Perry"}, {"name": "thread", "value": "16320-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_1_login"}]}