{"uuid": "7a3cc635-39af-41f0-9af6-e0842c7ae789", "children": ["612498fc-0e99-4975-bd34-65bd54b61309", "03f5015d-0575-4a63-b439-e83af0b786f1", "8ee3f357-f251-47e7-b784-d42b5d3eb380", "bbaa24c9-7909-4b7c-97ad-89ba10daa81d", "14c75f82-6e8a-4ff9-9931-0aab9e8f80bc", "a58a6b49-de65-4fad-b022-ef3df36327b7", "f5e980b2-21ec-43e1-bee0-6910acd98858", "c5594d22-0823-4339-ba89-e64b48b9f700", "3256e635-c38d-4ad9-86b3-4faeccc7643b", "db87de23-12e8-4a45-8e74-8ab9332c70b4", "8d2782a9-6dbe-4a09-b408-b7ac2685ff4e", "6c920998-b577-4555-a179-6e5723c89079", "f8cd0bf8-224d-40ff-bfeb-9a52b66aa5bc", "d4bfb7af-3396-4c51-b3c7-3bd424f58a98", "ee486b4f-9c08-4edc-97e9-2ff90ee8af9d", "303ac24e-a4bb-445d-b4de-92639580fc6f", "9658fd80-d105-4df4-bdd2-953d060f72f3", "806aa29c-0236-4914-8671-b567064f84e0", "6549dd16-f645-4a3a-8174-9c482efef60b", "7ef251f1-28d3-47bd-a7e3-71b537c76c20", "26ffb3a0-e6a9-40a0-95eb-2193499ca15d", "f509d708-6cea-4f83-a6e8-e71f253f1ac4", "bc34fe94-341c-4176-b45c-e3d3a2f47176", "db5071ee-aec9-4055-be89-3e8dcf311f30", "8493ac92-8426-467e-b218-0f1e17c4f2f8", "f92916c5-da85-4476-8082-f855cdce3420", "2a69e15c-a02d-4be7-bbc0-d31a3641eedb", "36734649-5534-4e29-8c15-f999ffcbe866", "2f200329-3d97-4842-bd09-341d036c8d5a", "3533857e-a365-4f14-a644-3999137ff33c", "ede73c41-4199-4a3c-9588-dde5ac8e6fd0", "d11eeec6-27d8-42d5-bba9-d2d0258e3472", "aff4b204-3f6b-4645-a7d8-bea793c7abc8", "f52337d9-c3f0-4549-be69-8c1ee6e61b52"], "befores": [{"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332400615, "stop": 1739332400617}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332402667, "stop": 1739332402676}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332404768, "stop": 1739332404791}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332406895, "stop": 1739332406898}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332408957, "stop": 1739332408964}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332411045, "stop": 1739332411053}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332413120, "stop": 1739332413129}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332415195, "stop": 1739332415202}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332417262, "stop": 1739332417265}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332419327, "stop": 1739332419330}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332421394, "stop": 1739332421403}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332423464, "stop": 1739332423473}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332425544, "stop": 1739332425547}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332427628, "stop": 1739332427634}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332429696, "stop": 1739332429703}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332431767, "stop": 1739332431774}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332433852, "stop": 1739332433859}, {"name": "logged_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n\tGetHandleVerifier [0x00007FF68C6502F5+28725]\n\t(No symbol) [0x00007FF68C5B2AE0]\n\t(No symbol) [0x00007FF68C444F39]\n\t(No symbol) [0x00007FF68C489214]\n\t(No symbol) [0x00007FF68C4BFE59]\n\t(No symbol) [0x00007FF68C4BA810]\n\t(No symbol) [0x00007FF68C4B98F3]\n\t(No symbol) [0x00007FF68C412EC5]\n\tGetHandleVerifier [0x00007FF68C97F30D+3366989]\n\tGetHandleVerifier [0x00007FF68C9912F0+3440688]\n\tGetHandleVerifier [0x00007FF68C9878FD+3401277]\n\tGetHandleVerifier [0x00007FF68C71AAAB+858091]\n\t(No symbol) [0x00007FF68C5BE74F]\n\t(No symbol) [0x00007FF68C411AD4]\n\tGetHandleVerifier [0x00007FF68C9ECB28+3815528]\n\tBaseThreadInitThunk [0x00007FF883A57374+20]\n\tRtlUserThreadStart [0x00007FF8841FCC91+33]\n\n", "trace": "  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\Projects\\WebUI\\src\\conftest.py\", line 205, in logged_driver\n    login_driver.do_login(config[\"username\"], config[\"password\"])\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 94, in do_login\n    self.open()\n  File \"D:\\Projects\\WebUI\\src\\pages\\LoginPage.py\", line 41, in open\n    return self.driver.title\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 374, in title\n    return self.execute(Command.GET_TITLE).get(\"value\", \"\")\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 354, in execute\n    self.error_handler.check_response(response)\n  File \"D:\\Projects\\WebUI\\.venv\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1739332435930, "stop": 1739332435938}], "start": 1739332435930, "stop": 1739332435965}